### ISSUE TITLE
SPLUNK_DB env var is not set in the container. All Indexes are writing into the docker.img

### ISSUE THREAD

**Issue by JoeStratton** [andrew207/splunk#17]
Believe I found the issue. I was able to stop it from growing the image by creating a new index with a new volume and not using the default. 

I think the '$SPLUNK_DB/audit/db ' is a bad value for all default indexs

**Comment by JoeStratton** [comment]
line 27 of the goplunk script is not working

**Comment by andrew207** [comment]
The container will send all indexed data to /splunkdata, it's up to the user to mount that as a volume if you don't want data written to docker.img. "Works for me" sorry, i'll leave this open for another week or so if you want to post your config and I'm happy to help -- there might be other inconsistencies in our environments. 

For example, here's my indexes.conf extract for an index where all the data goes to `/splunkdata` (as designated by formerly line 27 now line 30 of gosplunk.sh), a volume in the container and therefore not growing docker.img. 
```
[solar]
maxTotalDataSizeMB = 10240
coldPath = $SPLUNK_DB/solar/colddb
homePath = $SPLUNK_DB/solar/db
thawedPath = $SPLUNK_DB/solar/thaweddb
```

**Comment by andrew207** [comment]
For example, here's my indexes.conf extract for an index where all the data goes to /splunkdata (as designated by $SPLUNK_DB), a volume in the container and therefore not growing docker.img. 
`[solar]
maxTotalDataSizeMB = 10240
coldPath = $SPLUNK_DB/solar/colddb
homePath = $SPLUNK_DB/solar/db
thawedPath = $SPLUNK_DB/solar/thaweddb`

**Comment by andrew207** [comment]
Closing as no response // no issue found on my end.
