### ISSUE TITLE
Handling upgrades with persisted /opt/splunk/etc/apps?

### ISSUE THREAD

**Issue by dtomlinson91** [andrew207/splunk#28]
Hey

Struggling to understand how Splunk handles upgrades with this image. I've had a read through and I can't see anything in the Docker image that handles the upgrade on `/opt/splunk/etc/apps`.

I've installed the container fresh on the latest 8.2.1 version on Unraid. How can I handle an upgrade (say theoretically) to Splunk 9?

The apps folder with a bind Mount will always overwrite the files inside the container on container start from now on. This essentially fixes these files to 8.2.1 doesn’t it? Manually mapping `apps/*/local` for each and every app isn't really practical long term.

Does this image handle it? Or is this something that needs to be considered?

**Comment by andrew207** [comment]
The image doesn't handle it right now. If Splunk 9 comes out with some massive breaking change I'll consider putting a silent migration component in the startup shell script, but it'll depend on what the changes look like.
